[package]
name = "zvolrescue-io"
description = "Read-only access to devices and disk images for zvolrescue. The only crate that may ever contain unsafe code."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
