[package]
name = "zfs-ondisk"
description = "Pure parsers for ZFS on-disk structures (labels, uberblocks, block pointers). No I/O."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
edonr = { path = "../edonr", version = "0.0.1" }
sha2 = { workspace = true }
lz4_flex = { workspace = true }
flate2 = { workspace = true }
ruzstd = { workspace = true }
blake3 = { workspace = true }

[lints]
workspace = true
